name = "recaptchav2"
main = "functions/submit.js"
compatibility_date = "2024-05-01"

[env]
RECAPTCHA_SECRET = "@recaptcha_secret"  # Set via Cloudflare dashboard

[[functions]]
directory = "./functions"